# Generated by Django 4.2.5 on 2024-02-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=255)),
                ('Product_category', models.CharField(max_length=255)),
                ('Product_image', models.ImageField(upload_to='product_img')),
                ('Product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Product_quantity', models.IntegerField()),
                ('Product_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
