# Generated by Django 4.2.5 on 2024-02-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0002_category_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
