# Generated by Django 4.2.5 on 2024-02-20 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0003_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=255)),
                ('Product_category', models.CharField(max_length=255)),
                ('Product_image', models.ImageField(upload_to='product_img')),
                ('Product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Product_quantity', models.IntegerField()),
                ('Product_description', models.CharField(max_length=500)),
                ('Product_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
