# Generated by Django 4.2.5 on 2024-02-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0004_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
