# Generated by Django 5.0.4 on 2024-04-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Contact',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
